version: '3.5'
services:
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    restart: unless-stopped
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    container_name: perf_elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.1
    restart: unless-stopped
    ports:
      - 127.0.0.1:5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://perf_elastic:9200

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf

  django_h2:
    build:
      context: .
    volumes:
      - ./configs/h2_gunicorn.conf.py:/opt/gunicorn.conf.py
      - ../django_h2:/opt/django_h2
    environment:
      SCRIPT_NAME: /django_h2

  django_asgi:
    build:
      context: .
    volumes:
      - ./configs/asgi_gunicorn.conf.py:/opt/gunicorn.conf.py
